### PR TITLE
Add github action to publish to Github Docker Registry

### PR DESCRIPTION
**Pull request by phuonghuynh**
- The action listening on only branch "docker" for now
- Remove Travis CI

### CODE REVIEW

**Comment by ronaldtse** [comment]
The job seems to be still failing...

**Comment by phuonghuynh** [comment]
You mean `Cirrus CI / Docker Build` ?

**Comment by ronaldtse** [comment]
@phuonghuynh why are we using Cirrus? We should be using GitHub Actions.

**Comment by phuonghuynh** [comment]
Nope, we are using GHA, listening only branch "docker", when the code is ready to deploy, we should merge to this branch to trigger GHA for docker deployment.
I don't know who enable CirrcusCI

**Comment by phuonghuynh** [comment]
@ronaldtse could we disable CirrcusCI check?

**Comment by ronaldtse** [comment]
@phuonghuynh I will disable it, not easy to find 😓

**Comment by ronaldtse** [comment]
@phuonghuynh couldn't find out how to disable it for this repo, so I just uninstalled Cirrus for the whole account :wink:

**Comment by ronaldtse** [comment]
@phuonghuynh can we merge this soon?

**Pull request merged**
