### PR TITLE
Fixes related to the owner appeal process

### PR DESCRIPTION
**Pull request by florianesser**
This fixes several GUI functions related to the owner appeal process and adds a couple of new feature:

- fixes that after initiating an appeal the proposal was in Limbo state
- adds to do count badge for the Register Owner menu entry
- adds option for the Register Manager to end the appeal period

### CODE REVIEW

**Comment by phuonghuynh** [comment]
@florianesser could you help to resolve the conflicting ? ^

**Comment by florianesser** [comment]
> @florianesser could you help to resolve the conflicting ? ^

Of course, I'll rebase this after https://github.com/ISO-TC211/iso-geodetic-registry/pull/48 is merged

**Comment by phuonghuynh** [comment]
> #48 is merged

Merged ^

**Comment by florianesser** [comment]
@phuonghuynh Ready for merge

**Pull request merged**
