### PR TITLE
added Angular 8 project and updated readme

### PR DESCRIPTION
**Pull request by bbehling**

### CODE REVIEW

**Comment by phuonghuynh** [comment]
Thanks @bbehling

**Comment by phuonghuynh** [comment]
@bbehling look like "angular-app" in this PR does not calling our "-rest-api" to demo the homepage ? Could you make the homepage work with "-rest-api" for demostation? 

Also, i can see that there are some "jar" files included in this PR, sample, https://github.com/ISO-TC211/iso-geodetic-registry/pull/64/files#diff-74da69f3152d84cef92b7cba8233f715
What are these files used for ?

**Comment by phuonghuynh** [comment]
@bbehling FYI; i checked out your branch in this PR, and modify some files, committed to new branch here, https://github.com/ISO-TC211/iso-geodetic-registry/tree/pr64

I will continue to work on finalizing the HomePage for your reference. Also, we need to rework on styling for new boostrap-4x added (old client code using bootstrap-3x)

**Comment by bbehling** [comment]
> @bbehling look like "angular-app" in this PR does not calling our "-rest-api" to demo the homepage ? Could you make the homepage work with "-rest-api" for demostation?
> 
> Also, i can see that there are some "jar" files included in this PR, sample, https://github.com/ISO-TC211/iso-geodetic-registry/pull/64/files#diff-74da69f3152d84cef92b7cba8233f715
> What are these files used for ?

Aren't these supposed to be in the gitignore file?

**Comment by bbehling** [comment]
> @bbehling FYI; i checked out your branch in this PR, and modify some files, committed to new branch here, https://github.com/ISO-TC211/iso-geodetic-registry/tree/pr64
> 
> I will continue to work on finalizing the HomePage for your reference. Also, we need to rework on styling for new boostrap-4x added (old client code using bootstrap-3x)

Lets not copy bootstrap 3 css code into Bootstrap 4. Thats going to be come a maintenance nightmare. Let me take a look at the differences between 4 and 3, and I'll adjust for any visual differences without Bootstrap 3 code.

**Comment by bbehling** [comment]
> @bbehling look like "angular-app" in this PR does not calling our "-rest-api" to demo the homepage ? Could you make the homepage work with "-rest-api" for demostation?
> 
> Also, i can see that there are some "jar" files included in this PR, sample, https://github.com/ISO-TC211/iso-geodetic-registry/pull/64/files#diff-74da69f3152d84cef92b7cba8233f715
> What are these files used for ?

I found a CORS conflicts in local dev. I'll add a CORS filter to the rest-api to resolve this.

**Comment by bbehling** [comment]
Moving this to another pull request

**Pull request closed without merging**
